// ============================================================
// Git Mirror Service
// Daily export: All content → Markdown + YAML frontmatter
// "If NEXUS dies, you own your IP"
// ============================================================

import type { SchedulerEnv } from "../index";

export interface ExportProduct {
  id: string;
  name: string;
  niche_id: string;
  status: string;
  created_at: string;
  user_input?: Record<string, unknown>;
}

export class GitMirror {
  private readonly BATCH_SIZE = 100;
  
  constructor(private env: SchedulerEnv) {}

  // Export all content to Git-compatible format
  async exportAllContent(): Promise<{ success: boolean; exported: number; url?: string }> {
    console.log('[GIT MIRROR] Starting content export...');
    
    try {
      // Get all products
      const { results: products } = await this.env.DB.prepare(`
        SELECT id, name, niche_id, status, created_at, user_input
        FROM products
        ORDER BY created_at DESC
      `).all<ExportProduct>();
      
      if (!products || products.length === 0) {
        console.log('[GIT MIRROR] No products to export');
        return { success: true, exported: 0 };
      }
      
      // Generate markdown exports
      const exports: Array<{ path: string; content: string }> = [];
      
      for (const product of products) {
        const markdown = this.generateProductMarkdown(product);
        const date = product.created_at.slice(0, 10);
        const slug = this.slugify(product.name || 'untitled');
        
        exports.push({
          path: `content/${product.niche_id}/${date}-${slug}.md`,
          content: markdown,
        });
      }
      
      // Also export as single JSON backup
      const jsonBackup = JSON.stringify(products, null, 2);
      exports.push({
        path: `backups/products-${new Date().toISOString().slice(0, 10)}.json`,
        content: jsonBackup,
      });
      
      // Store in R2 (Git-compatible structure)
      for (const item of exports) {
        await this.env.NEXUS_R2.put(item.path, item.content, {
          customMetadata: {
            exported_at: new Date().toISOString(),
            type: 'git_mirror',
          }
        });
      }
      
      // If Git repo configured, push to Git
      if (this.env.GIT_MIRROR_REPO && this.env.GIT_MIRROR_TOKEN) {
        await this.pushToGit(exports);
      }
      
      console.log(`[GIT MIRROR] Exported ${exports.length} files`);
      
      return {
        success: true,
        exported: exports.length,
        url: `r2://git-mirror/content/`
      };
      
    } catch (error) {
      console.error('[GIT MIRROR] Export failed:', error);
      return { success: false, exported: 0 };
    }
  }

  // Generate Markdown with YAML frontmatter for a product
  private generateProductMarkdown(product: ExportProduct): string {
    const frontmatter: Record<string, unknown> = {
      id: product.id,
      title: product.name,
      niche: product.niche_id,
      status: product.status,
      created_at: product.created_at,
      exported_at: new Date().toISOString(),
    };
    
    // Add user input if present
    if (product.user_input) {
      for (const [key, value] of Object.entries(product.user_input)) {
        if (!frontmatter[key]) {
          frontmatter[key] = value;
        }
      }
    }
    
    // Build YAML frontmatter
    const yaml = Object.entries(frontmatter)
      .map(([key, value]) => {
        if (typeof value === 'string' && value.includes('\n')) {
          return `${key}: |\n  ${value.replace(/\n/g, '\n  ')}`;
        }
        return `${key}: ${JSON.stringify(value)}`;
      })
      .join('\n');
    
    return `---\n${yaml}\n---\n\n# ${product.name || 'Untitled'}\n\n*Exported from NEXUS on ${new Date().toISOString()}*\n\n<!--
This file was auto-generated by NEXUS Git Mirror.
If NEXUS dies, you own your IP. This is your backup.
-->
`;
  }

  // Push exports to Git repository
  private async pushToGit(exports: Array<{ path: string; content: string }>): Promise<void> {
    // In a real implementation, this would:
    // 1. Clone the repo (or use GitHub API)
    // 2. Create commits with the exported files
    // 3. Push to the remote
    
    // For Cloudflare Workers, we'd typically use the GitHub API
    const repo = this.env.GIT_MIRROR_REPO;
    const token = this.env.GIT_MIRROR_TOKEN;
    
    if (!repo || !token) return;
    
    const [owner, repoName] = repo.split('/');
    const apiUrl = `https://api.github.com/repos/${owner}/${repoName}`;
    
    const timestamp = new Date().toISOString();
    const commitMessage = `NEXUS auto-export: ${timestamp}`;
    
    // Create/update files via GitHub API
    for (const item of exports.slice(0, 10)) { // Limit to 10 files per run
      try {
        // Check if file exists
        const getResponse = await fetch(`${apiUrl}/contents/${item.path}`, {
          headers: { 'Authorization': `token ${token}` }
        });
        
        const contentBase64 = btoa(unescape(encodeURIComponent(item.content)));
        
        if (getResponse.status === 404) {
          // Create new file
          await fetch(`${apiUrl}/contents/${item.path}`, {
            method: 'PUT',
            headers: {
              'Authorization': `token ${token}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              message: commitMessage,
              content: contentBase64,
            })
          });
        } else {
          // Update existing file
          const existing = await getResponse.json();
          await fetch(`${apiUrl}/contents/${item.path}`, {
            method: 'PUT',
            headers: {
              'Authorization': `token ${token}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              message: commitMessage,
              content: contentBase64,
              sha: existing.sha,
            })
          });
        }
      } catch (error) {
        console.error(`[GIT MIRROR] Failed to push ${item.path}:`, error);
      }
    }
    
    console.log('[GIT MIRROR] Pushed to Git repository');
  }

  // Get export status
  async getStatus(): Promise<{
    last_export: string | null;
    total_files: number;
    repo_configured: boolean;
  }> {
    // List objects in R2
    const listed = await this.env.NEXUS_R2.list({ prefix: 'content/' });
    
    // Get last export time from KV
    const lastExport = await this.env.NEXUS_KV.get('git_mirror:last_export');
    
    return {
      last_export: lastExport,
      total_files: listed.objects?.length || 0,
      repo_configured: !!(this.env.GIT_MIRROR_REPO && this.env.GIT_MIRROR_TOKEN),
    };
  }

  // Helper: Create slug from string
  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 50);
  }
}
